package main

import (
	"math/rand"
	"time"
)

func main() {
	chooseWord()
}

func chooseWord() {
	rand.Seed(time.Now().UnixNano())

	var strArray [20]string
	strArray[0] = "super-glue"
	strArray[1] = "velo"
	strArray[2] = "voiture"
	strArray[3] = "chaussure"
	strArray[4] = "disjoncteur"
	strArray[5] = "eglise"
	strArray[6] = "machine a laver"
	strArray[7] = "aspirateur"
	strArray[8] = "ecrevisse"
	strArray[9] = "koala"
	strArray[10] = "montre a gousset"
	strArray[11] = "jagermeister"
	strArray[12] = "trepied"
	strArray[13] = "mirroir"
	strArray[14] = "starbucks"
	strArray[15] = "costume"
	strArray[16] = "ange"
	strArray[17] = "espace"
	strArray[18] = "eclipse"
	strArray[19] = "ceinture"

	var easyPiWords [50]string
	easyPiWords[0] = "Angel"
	easyPiWords[1] = "Eyeball"
	easyPiWords[2] = "Pizza"
	easyPiWords[3] = "Angry"
	easyPiWords[4] = "Fireworks"
	easyPiWords[5] = "Pumpkin"
	easyPiWords[6] = "Baby"
	easyPiWords[7] = "Flower"
	easyPiWords[8] = "Rainbow"
	easyPiWords[9] = "Beard"
	easyPiWords[10] = "Flying saucer"
	easyPiWords[11] = "Recycle"
	easyPiWords[12] = "Bible"
	easyPiWords[13] = "Giraffe"
	easyPiWords[14] = "Sand castle"
	easyPiWords[15] = "Bikini"
	easyPiWords[16] = "Glasses"
	easyPiWords[17] = "Snowflake"
	easyPiWords[18] = "Book"
	easyPiWords[19] = "High heel"
	easyPiWords[20] = "Stairs"
	easyPiWords[21] = "Bucket"
	easyPiWords[22] = "Ice cream cone"
	easyPiWords[23] = "Starfish"
	easyPiWords[24] = "Bumble bee"
	easyPiWords[25] = "Igloo"
	easyPiWords[26] = "Strawberry"
	easyPiWords[27] = "Butterfly"
	easyPiWords[28] = "Lady bug"
	easyPiWords[29] = "Sun"
	easyPiWords[30] = "Camera"
	easyPiWords[31] = "Lamp"
	easyPiWords[32] = "Tire"
	easyPiWords[33] = "Cat"
	easyPiWords[34] = "Lion"
	easyPiWords[35] = "Toast"
	easyPiWords[36] = "Church"
	easyPiWords[37] = "Mailbox"
	easyPiWords[38] = "Toothbrush"
	easyPiWords[39] = "Crayon"
	easyPiWords[40] = "Night"
	easyPiWords[41] = "Toothpaste"
	easyPiWords[42] = "Dolphin"
	easyPiWords[43] = "Nose"
	easyPiWords[44] = "Truck"
	easyPiWords[45] = "Egg"
	easyPiWords[46] = "Olympics"
	easyPiWords[47] = "Volleyball"
	easyPiWords[48] = "Eiffel Tower"
	easyPiWords[49] = "Peanut"

	var mediumPiWords [50]string
	mediumPiWords[0] = "Abraham Lincoln"
	mediumPiWords[1] = "Kiss"
	mediumPiWords[2] = "Pigtails"
	mediumPiWords[3] = "Brain"
	mediumPiWords[4] = "Kitten"
	mediumPiWords[5] = "Playground"
	mediumPiWords[6] = "Bubble bath"
	mediumPiWords[7] = "Kiwi"
	mediumPiWords[8] = "Pumpkin pie"
	mediumPiWords[9] = "Buckle"
	mediumPiWords[10] = "Lipstick"
	mediumPiWords[11] = "Raindrop"
	mediumPiWords[12] = "Bus"
	mediumPiWords[13] = "Lobster"
	mediumPiWords[14] = "Robot"
	mediumPiWords[15] = "Car accident"
	mediumPiWords[16] = "Lollipop"
	mediumPiWords[17] = "Sand castle"
	mediumPiWords[18] = "Castle"
	mediumPiWords[19] = "Magnet"
	mediumPiWords[20] = "Slipper"
	mediumPiWords[21] = "Chain saw"
	mediumPiWords[22] = "Megaphone"
	mediumPiWords[23] = "Snowball"
	mediumPiWords[24] = "Circus tent"
	mediumPiWords[25] = "Mermaid"
	mediumPiWords[26] = "Sprinkler"
	mediumPiWords[27] = "Computer"
	mediumPiWords[28] = "Minivan"
	mediumPiWords[29] = "Statue of Liberty"
	mediumPiWords[30] = "Crib"
	mediumPiWords[31] = "Mount Rushmore"
	mediumPiWords[32] = "Tadpole"
	mediumPiWords[33] = "Dragon"
	mediumPiWords[34] = "Music"
	mediumPiWords[35] = "Teepee"
	mediumPiWords[36] = "Dumbbell"
	mediumPiWords[37] = "North pole"
	mediumPiWords[38] = "Telescope"
	mediumPiWords[39] = "Eel"
	mediumPiWords[40] = "Nurse"
	mediumPiWords[41] = "Train"
	mediumPiWords[42] = "Ferris wheel"
	mediumPiWords[43] = "Owl"
	mediumPiWords[44] = "Tricycle"
	mediumPiWords[45] = "Flag"
	mediumPiWords[46] = "Pacifier"
	mediumPiWords[47] = "Tutu"
	mediumPiWords[48] = "Junk mail"
	mediumPiWords[49] = "Piano"

	var hardPiWords [50]string
	hardPiWords[0] = "Attic"
	hardPiWords[1] = "Glue"
	hardPiWords[2] = "Pocket watch"
	hardPiWords[3] = "Back seat"
	hardPiWords[4] = "Highchair"
	hardPiWords[5] = "Rock band"
	hardPiWords[6] = "Birthday"
	hardPiWords[7] = "Hockey"
	hardPiWords[8] = "Sasquatch"
	hardPiWords[9] = "Black hole"
	hardPiWords[10] = "Hotel"
	hardPiWords[11] = "Scrambled eggs"
	hardPiWords[12] = "Blizzard"
	hardPiWords[13] = "Jump rope"
	hardPiWords[14] = "Seat belt"
	hardPiWords[15] = "Burrito"
	hardPiWords[16] = "Koala"
	hardPiWords[17] = "Skip"
	hardPiWords[18] = "Captain"
	hardPiWords[19] = "Leprechaun"
	hardPiWords[20] = "Solar eclipse"
	hardPiWords[21] = "Chandelier"
	hardPiWords[22] = "Light"
	hardPiWords[23] = "Space"
	hardPiWords[24] = "Crib"
	hardPiWords[25] = "Mask"
	hardPiWords[26] = "Stethoscope"
	hardPiWords[27] = "Cruise ship"
	hardPiWords[28] = "Mechanic"
	hardPiWords[29] = "Stork"
	hardPiWords[30] = "Dance"
	hardPiWords[31] = "Mom"
	hardPiWords[32] = "Sunburn"
	hardPiWords[33] = "Deodorant"
	hardPiWords[34] = "Mr Potato Head"
	hardPiWords[35] = "Thread"
	hardPiWords[36] = "Facebook"
	hardPiWords[37] = "Pantyhose"
	hardPiWords[38] = "Tourist"
	hardPiWords[39] = "Flat"
	hardPiWords[40] = "Paper plate"
	hardPiWords[41] = "United States"
	hardPiWords[42] = "Frame"
	hardPiWords[43] = "Photo"
	hardPiWords[44] = "WiFi"
	hardPiWords[45] = "Full moon"
	hardPiWords[46] = "Pilgram"
	hardPiWords[47] = "Zombie"
	hardPiWords[48] = "Game"
	hardPiWords[49] = "Pirate"

	index := rand.Intn(50)
	println(hardPiWords[index])

	index1 := rand.Intn(50)
	println(mediumPiWords[index1])

	index2 := rand.Intn(50)
	println(easyPiWords[index2])
}
